blacklight-base/src/main/res/layout/direct_message_conversation.xml
(cherry picked from commit d056f34)
啊，我觉得去掉那条不和谐的线会比较好看。。
=> remove edit text line

blacklight-base/src/main/java/info/papdt/blacklight/ui/comments/CommentOnActivity.java, blacklight-base/src/main/java/info/papdt/blacklight/ui/comments/ReplyToActivity.java, blacklight-base/src/main/java/info/papdt/blacklight/ui/statuses/NewPostActivity.java, blacklight-base/src/main/java/info/papdt/blacklight/ui/statuses/RepostActivity.java
=> fix draft iss

blacklight-base/src/main/java/info/papdt/blacklight/ui/statuses/SingleActivity.java, blacklight-base/src/main/java/info/papdt/blacklight/ui/statuses/UserTimeLineActivity.java, blacklight-base/src/main/res/layout/direct_message_conversation.xml, blacklight-base/src/main/res/layout/single.xml, blacklight-base/src/main/res/layout/user_timeline_activity.xml, libraries/SlidingUpPanel/build.gradle, libraries/SlidingUpPanel/src/main/java/com/sothree/slidinguppanel/SlidingUpPanelLayout.java, libraries/SlidingUpPanel/src/main/java/com/sothree/slidinguppanel/ViewDragHelper.java, libraries/SlidingUpPanel/src/main/res/values/attrs.xml
打算贡献点力量，code style有没有idea的配置文件
=> status UI polish

blacklight-base/src/main/res/layout/single.xml
=> blacklight-base: single weibo layout: variable tab width

app-snapshot/src/main/AndroidManifest.xml, app/src/main/AndroidManifest.xml, blacklight-base/src/main/java/info/papdt/blacklight/api/Constants.java, blacklight-base/src/main/java/info/papdt/blacklight/api/shorturl/ShortUrlApi.java, blacklight-base/src/main/java/info/papdt/blacklight/support/WeiboSpan.java, blacklight-base/src/main/java/info/papdt/blacklight/support/WeiboUrlUtility.java, blacklight-base/src/main/java/info/papdt/blacklight/ui/entry/UrlEntryActivity.java
=> add short url support to BlackLight

blacklight-base/src/main/java/info/papdt/blacklight/support/WeiboSpan.java
=> peter wrote code with a bug which has been fixed now

blacklight-base/src/main/java/info/papdt/blacklight/cache/database/DataBaseHelper.java, blacklight-base/src/main/java/info/papdt/blacklight/ui/settings/SettingsFragment.java
=> also clear cached data at database

blacklight-base/src/main/java/info/papdt/blacklight/ui/entry/UrlEntryActivity.java
=> UrlEntryActivity: load access token before parse short url

blacklight-base/src/main/res/values-zh-rCN/splashes.xml
add a new geng from fishroom of tuna
=> new geng from fishroom of tuna

blacklight-base/src/main/java/info/papdt/blacklight/support/WeiboUrlUtility.java, blacklight-base/src/main/java/info/papdt/blacklight/ui/entry/UrlEntryActivity.java
so there is no chance to set as default
=> forcing an app chooser for unknown url

blacklight-base/src/main/java/info/papdt/blacklight/service/ReminderService.java, blacklight-base/src/main/java/info/papdt/blacklight/support/Settings.java, blacklight-base/src/main/java/info/papdt/blacklight/ui/settings/SettingsFragment.java, blacklight-base/src/main/res/values-zh-rCN/strings.xml, blacklight-base/src/main/res/values-zh-rTW/strings.xml, blacklight-base/src/main/res/values/strings.xml, blacklight-base/src/main/res/xml/settings.xml
=> Now we can select notification type.

blacklight-base/src/main/java/info/papdt/blacklight/cache/file/FileCacheManager.java, blacklight-base/src/main/java/info/papdt/blacklight/ui/common/AbsImageActivity.java
=> Delete downloaded file if an error is thrown.

blacklight-base/src/main/res/layout/direct_message_conversation.xml
=> Use NewPostBackground for dm EditText background

blacklight-base/src/main/java/info/papdt/blacklight/support/PermissionUtility.java, blacklight-base/src/main/java/info/papdt/blacklight/ui/entry/EntryActivity.java, blacklight-base/src/main/java/info/papdt/blacklight/ui/settings/SettingsFragment.java
let PermissionUtility to do its job
=> PermissionUtility: add hasStoragePermission

blacklight-base/src/main/java/info/papdt/blacklight/api/Constants.java, blacklight-base/src/main/java/info/papdt/blacklight/api/statuses/QueryIdApi.java, blacklight-base/src/main/java/info/papdt/blacklight/support/WeiboUrlUtility.java
=> parse Single weibo url and enter SingleActivity directly

blacklight-base/src/main/java/info/papdt/blacklight/ui/entry/UrlEntryActivity.java
=> use AsyncTask from support

blacklight-base/src/main/java/info/papdt/blacklight/service/ReminderService.java, blacklight-base/src/main/java/info/papdt/blacklight/support/Reminders.java
=> Use AsyncTask for notification.

blacklight-base/src/main/java/info/papdt/blacklight/model/UserModel.java
Make following status correct when the activity is shown.
=> Write follow_me into parcel.

app-snapshot/src/main/AndroidManifest.xml, app/src/main/AndroidManifest.xml, blacklight-base/src/main/java/info/papdt/blacklight/ui/statuses/UserProfileActivity.java, blacklight-base/src/main/java/info/papdt/blacklight/ui/statuses/UserTimeLineActivity.java, blacklight-base/src/main/res/layout/user_profile.xml, blacklight-base/src/main/res/layout/user_profile_item.xml, blacklight-base/src/main/res/values-zh-rCN/strings.xml, blacklight-base/src/main/res/values/strings.xml
=> Add activity for extra user profile

blacklight-base/src/main/java/info/papdt/blacklight/support/WeiboUrlUtility.java, blacklight-base/src/main/java/info/papdt/blacklight/ui/entry/UrlEntryActivity.java
see: https://code.google.com/p/android-developer-preview/issues/detail?id=2353
also fix #1901
=> UrlEntryActivity: fix a crash on Marshmallow

blacklight-base/src/main/java/info/papdt/blacklight/ui/main/MainActivity.java, libraries/PersistentSearch/src/main/java/com/quinny898/library/persistentsearch/SearchBox.java
=> add speech input method support for search box
